server:
  port: 8888
  
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: /home/rafael/Github/Microservicos/configuration/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rafaelcarvalhocaetano/Microservicos
          search-paths: configuration